// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'API-KEY',
    appId: '1:921894286137:web:9b6ed229424a6c5c2faee8',
    messagingSenderId: '921894286137',
    projectId: 'jphacks-dev-8d57d',
    authDomain: 'jphacks-dev-8d57d.firebaseapp.com',
    storageBucket: 'jphacks-dev-8d57d.appspot.com',
    measurementId: 'G-FHYZFSZH29',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'API-KEY',
    appId: '1:921894286137:android:9952d9e6d0b7d59b2faee8',
    messagingSenderId: '921894286137',
    projectId: 'jphacks-dev-8d57d',
    storageBucket: 'jphacks-dev-8d57d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'API-KEY',
    appId: '1:921894286137:ios:175ff1217abbdfd42faee8',
    messagingSenderId: '921894286137',
    projectId: 'jphacks-dev-8d57d',
    storageBucket: 'jphacks-dev-8d57d.appspot.com',
    iosBundleId: 'net.hekuta',
  );
}
