"""Add init models

Revision ID: 21b299d5addf
Revises: 
Create Date: 2024-10-27 02:54:22.254449

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "21b299d5addf"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "gps_musics",
        sa.Column("gps_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("uid", sa.String(length=128), nullable=False),
        sa.Column("music_url", sa.String(length=256), nullable=False),
        sa.Column("latitude", sa.DOUBLE_PRECISION(), nullable=False),
        sa.Column("longitude", sa.DOUBLE_PRECISION(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("gps_id"),
        sa.UniqueConstraint("uid"),
    )
    op.create_table(
        "users",
        sa.Column("uid", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=16), nullable=True),
        sa.Column("age", sa.Integer(), nullable=True),
        sa.Column("gender", sa.Integer(), nullable=True),
        sa.Column("listen_genre_id", sa.Integer(), nullable=True),
        sa.Column("home_location", sa.String(length=32), nullable=True),
        sa.Column("bio", sa.String(length=64), nullable=True),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("email_verified", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("uid"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("uid"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    op.drop_table("gps_musics")
    # ### end Alembic commands ###
