"""update users table

Revision ID: 4379485bbd6d
Revises: d0fc6f17198e
Create Date: 2024-10-23 04:09:45.735064

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4379485bbd6d"
down_revision = "d0fc6f17198e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "name", existing_type=sa.VARCHAR(length=16), nullable=True)
    op.alter_column("users", "age", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("users", "gender", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column(
        "users", "listen_genre_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.create_unique_constraint(None, "users", ["uid"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.alter_column(
        "users", "listen_genre_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column("users", "gender", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("users", "age", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column(
        "users", "name", existing_type=sa.VARCHAR(length=16), nullable=False
    )
    # ### end Alembic commands ###
