"""Add teble

Revision ID: 1c410a179539
Revises: 
Create Date: 2024-10-27 05:20:02.583776

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1c410a179539"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "gps_musics",
        "latitude",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=10, scale=6),
        existing_nullable=False,
    )
    op.alter_column(
        "gps_musics",
        "longitude",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=10, scale=6),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "gps_musics",
        "longitude",
        existing_type=sa.Numeric(precision=10, scale=6),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=False,
    )
    op.alter_column(
        "gps_musics",
        "latitude",
        existing_type=sa.Numeric(precision=10, scale=6),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
