name: app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  go_router: ^14.3.0
  provider: ^6.1.2
  url_launcher: ^6.3.1
  app_links: ^6.3.2
  shadcn_ui: ^0.13.5
  firebase_dynamic_links: ^6.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true